### ISSUE TITLE
Update for Django 2.0.3?

### ISSUE THREAD

**Issue by slimandslam** [v1k45/ponynote#1]
On a Macbook Pro using Python 3.6.4, I install your ponynote code and do the following in the virtual environment:

pip install django
pip install django-node
pip install django-rest-framework
pip install django-webpack-loader
pip install optional-django
sudo npm install -g create-react-app
cd ponynote/frontend
npm install webpack-bundle-tracker --save-dev
cd ponynote
./manage.py migrate

All of that works fine.  
Then, in terminal window #1, while in the virtual env I do:
$ ./manage.py runserver

And in terminal window #2, I cd to the frontend dir and while in the virtual env I do:
$ yarn start

Everything works fine and I see the ponynote app in the browser window.

However, when I try to add notes by clicking on the "Save Note" button, I just get a bunch of JS errors:

> [Log] [HMR] Waiting for update signal from WDS... (bundle.js, line 39833)
> [Error] Unhandled Promise Rejection: SyntaxError (DOM Exception 12): The string did not match the expected pattern.
> 	(anonymous function)
> 	promiseReactionJob
> [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (notes, line 0) http://localhost:3000/api/notes/

Do you know what's going on?

**Comment by v1k45** [comment]
Seems like the URL returned 404. You are probably sending request to wrong host.

It should be http://localhost:8000/api/notes/

Please note that this project is a hybrid approach for SPAs in django where the frontend and backend are in same repository.

If you wish to maintain a standalone client app, then you need take few extra steps like allowing CORS between your client and server.

**Comment by v1k45** [comment]
Also, the project is pretty straight forward, it should work with Django2+ with minor modifications like the `url` functions in project urls.

**Comment by v1k45** [comment]
Another thing, If you are directly cloning this repository, you don't need to run any other commands than `pip install -r requirements.txt` and `npm install` to set up the project.  And then follow the tutorial to get run the project.

**Comment by slimandslam** [comment]
I see. So, "yarn start" automatically launches http://localhost:3000 but I need to manually enter http://localhost:8000 to see the app. It works fine now. Thanks.
